- name: Install utils packages
  become: true
  apt:
    name:
      - xsel
      - htop
      - tree
      - jq
      - trash-cli
      - ripgrep
    install_recommends: no

- name: Install gron
  become: true
  unarchive:
    src: https://github.com/tomnomnom/gron/releases/download/v0.6.1/gron-linux-amd64-0.6.1.tgz
    dest: /usr/local/bin
    remote_src: yes

- name: Install fd
  become: true
  apt:
    deb: https://github.com/sharkdp/fd/releases/download/v8.3.1/fd_8.3.1_amd64.deb


- name: Install thefuck
  become: true
  pip:
    name: thefuck

